### ISSUE TITLE
加载预训练模型出错

### ISSUE THREAD

**Issue by shaieesss** [franciscoliu/graphprompter#6]
trainable params: 23642112 || all params: 6762057728 || trainable%: 0.3496289583879755
  0%|                                                                                                             | 0/341025 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/zhangwenxin/pro/graphprompter/train.py", line 140, in <module>
    main(args)
  File "/home/zhangwenxin/pro/graphprompter/train.py", line 69, in main
    loss = model(batch)
  File "/home/zhangwenxin/anaconda3/envs/x/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zhangwenxin/anaconda3/envs/x/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhangwenxin/pro/graphprompter/src/model/graph_llm.py", line 127, in forward
    pad_embeds = self.word_embedding(torch.tensor(self.tokenizer.pad_token_id)).unsqueeze(0)
  File "/home/zhangwenxin/anaconda3/envs/x/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zhangwenxin/anaconda3/envs/x/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/zhangwenxin/anaconda3/envs/x/lib/python3.9/site-packages/torch/nn/modules/sparse.py", line 163, in forward
    return F.embedding(
  File "/home/zhangwenxin/anaconda3/envs/x/lib/python3.9/site-packages/torch/nn/functional.py", line 2237, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)

**Comment by franciscoliu** [comment]
Hi, thanks for raising this problem. As the problem reports, you need to move all tensors to be on the same device. Make sure you use the same "device" when you load the model.

**Comment by nxlogn** [comment]
me too, have you solved it?

**Comment by shaieesss** [comment]
change it to single GPU

| |
msezwx
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年10月24日 14:41 |
| 收件人 | franciscoliu/graphprompter ***@***.***> |
| 抄送人 | sdaioje ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [franciscoliu/graphprompter] 加载预训练模型出错 (Issue #6) |

me too, have you solved it?
