### ISSUE TITLE
About Llama Model

### ISSUE THREAD

**Issue by DuanhaoranCC** [franciscoliu/graphprompter#7]
![image](https://github.com/user-attachments/assets/cfd91f87-3d44-4437-8b01-3c91daac5833)
![image](https://github.com/user-attachments/assets/36064f95-0bad-42e3-a391-bf7f6e3aa31b)

Hello, I configured the path according to the picture above, but it gives me an error, what is the reason for this?

Error Information:
```linux
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\envs\kg\lib\site-packages\transformers\utils\hub.py", line 402, in cached_file
    resolved_file = hf_hub_download(
  File "C:\Users\admin\anaconda3\envs\kg\lib\site-packages\huggingface_hub\utils\_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\admin\anaconda3\envs\kg\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "C:\Users\admin\anaconda3\envs\kg\lib\site-packages\huggingface_hub\utils\_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: '[E:\llama3\Meta-Llama-3-8B\tokenizer.model]'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\graphprompter-main\train.py", line 139, in <module>
    main(args)
  File "E:\graphprompter-main\train.py", line 44, in main
    model = load_model[args.model_name](graph=dataset.graph, graph_type=dataset.graph_type, prompt=dataset.prompt, args=args)
  File "E:\graphprompter-main\src\model\graph_llm.py", line 41, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(args.llm_model_path, use_fast=False, revision=kwargs["revision"])
  File "C:\Users\admin\anaconda3\envs\kg\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 834, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\admin\anaconda3\envs\kg\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 666, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "C:\Users\admin\anaconda3\envs\kg\lib\site-packages\transformers\utils\hub.py", line 466, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: '[E:\llama3\Meta-Llama-3-8B\tokenizer.model]'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

```

**Comment by franciscoliu** [comment]
Hi Alisa, 

First of all, I think you shouldn't include "[]" when you put the directory there. Secondly, I think that's not the way how to put up the local model there. Please refer to [https://stackoverflow.com/questions/64001128/load-a-pre-trained-model-from-disk-with-huggingface-transformers](https://stackoverflow.com/questions/64001128/load-a-pre-trained-model-from-disk-with-huggingface-transformers.) Make sure your directory is correct.

**Comment by DuanhaoranCC** [comment]
Thank you for being so helpful.
Because I download Llama from Meta, the code load model by huggingface.
The error is solved.
